require:
  - standard
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - db/schema.rb
    - bin/*

Bundler/OrderedGems:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Style/Send:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/TimesMap:
  Enabled: true
