# fly.toml app configuration file generated for visualizer on 2023-11-11T20:39:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "visualizer"
primary_region = "fra"
console_command = "/rails/bin/rails console"

[processes]
  app = "foreman start --procfile=Procfile.fly"

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  h2_backend = true
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 500
    soft_limit = 400

[checks]
  [checks.up]
    grace_period = "10s"
    interval = "15s"
    timeout = "2s"
    port = 3000
    type = "tcp"
