# fly.toml app configuration file generated for visualizer on 2023-11-11T20:39:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "visualizer"
primary_region = "fra"
console_command = "/rails/bin/rails console"

[processes]
  app = "foreman start --procfile=Procfile.fly"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  processes = ["app"]
