default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [real_time, high, default, low]

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
