:concurrency: 5
:queues:
  - critical
  - default
  - low
:scheduler:
  :schedule:
    SharedShotCleanupJob:
      every: 1 hour
    FillAutocompleteValuesJob:
      every: 1 hour
    DuplicateStripeSubscriptionsJob:
      every: ['1 day', first_in: '5m']
    AirtableWebhookRefreshJob:
      every: ['6 day', first_in: '5m']
