default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        shared_shot_cleanup_job:
          class: SharedShotCleanupJob
          schedule: "@hourly"
        fill_autocomplete_values_job:
          class: FillAutocompleteValuesJob
          schedule: "@hourly"
        duplicate_stripe_subscriptions_job:
          class: DuplicateStripeSubscriptionsJob
          schedule: "@daily"
        populate_subscriptions_job:
          class: PopulateSubscriptionsJob
          schedule: "@daily"
        airtable_webhook_refresh_all_job:
          class: AirtableWebhookRefreshAllJob
          schedule: "0 0 */6 * *"
  workers:
    - queues: [real_time, high, default, low]

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
