default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        shared_shot_cleanup_job:
          class: SharedShotCleanupJob
          schedule: "@hourly"
        fill_autocomplete_values_job:
          class: FillAutocompleteValuesJob
          schedule: "@hourly"
        duplicate_stripe_subscriptions_job:
          class: DuplicateStripeSubscriptionsJob
          schedule: "@daily"
        airtable_webhook_refresh_all_job:
          class: AirtableWebhookRefreshAllJob
          schedule: "0 0 */6 * *"
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 2
    - queues: [critical, real_time, default, low]
      threads: 5
      polling_interval: 0.1
      processes: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
