name: Fly Deploy
on: workflow_call
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: FLY_REGISTRY_HOST=registry2.fly.io flyctl deploy --remote-only -e APP_REVISION="${{ github.sha }}"
