name: Main Branch

on:
  push:
    branches: [main]

jobs:
  call-ruby-tests:
    name: Call Ruby Tests
    uses: ./.github/workflows/ruby-tests.yml
    secrets: inherit
  call-fly:
    name: Call Fly
    needs: call-ruby-tests
    uses: ./.github/workflows/fly.yml
    secrets: inherit
