name: Ruby Tests
on: workflow_call
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0-preview3
          bundler-cache: true

      - name: Install postgres headers
        run: sudo apt-get install libpq-dev

      - name: Setup database
        run: bin/rails db:create db:migrate

      - name: Unit Tests
        run: bin/rails test
